### ISSUE TITLE
Incompatible with Rails 5.2.0.rc1

### ISSUE THREAD

**Issue by carlosramireziii** [OffgridElectric/rails-data-migrations#8]
I just upgraded to the latest edge version of Rails (v5.2.0.rc1) and it appears to have included a large refactoring of the migration internals. These changes seem to be breaking RailsDataMigrations (mainly because ActiveRecord::Migrator no longer has class methods; instead it makes use of an instance of MigrationContext to perform the operations).

See here: https://github.com/rails/rails/commit/a2827ec9811b5012e8e366011fd44c8eb53fc714#diff-8d3c44120f7b67ff79e2fbe6a40d0ad6

**Comment by serggl** [comment]
@carlosramireziii thank you for the report. I got a fix for this in `rails-5.2` branch, but I still want to wait until 5.2 will be officially released before I will merge it to master

**Comment by carlosramireziii** [comment]
Awesome! Thanks for rolling that out so quickly. Totally makes sense to wait until 5.2 is official to roll this out. I'll test it out on the project I'm working on using the RC and let you know if I notice anything. 

Thanks again!

**Comment by carlosramireziii** [comment]
I think the Rails 5.2 support has been merged into master, correct? If so, should we close this issue?

**Comment by serggl** [comment]
yep
